# Generated by Django 4.2.7 on 2024-02-06 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_job_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='applicantdetails',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.student'),
        ),
    ]
